<?php

namespace TecnoSpeed\Plugnotas\Enums;

enum CstPisEnum: string
{
    case OPERACAO_TRIBUTAVEL_ALIQUOTA_NORMAL = '01';
    case OPERACAO_TRIBUTAVEL_ALIQUOTA_DIFERENCIADA = '02';
    case OPERACAO_TRIBUTAVEL_POR_UNIDADE = '03';
    case OPERACAO_TRIBUTAVEL_MONOFASICA = '04';
    case OPERACAO_TRIBUTAVEL_SUBSTITUICAO_TRIBUTARIA = '05';
    case OPERACAO_TRIBUTAVEL_ALIQUOTA_ZERO = '06';
    case OPERACAO_ISENTA = '07';
    case OPERACAO_SEM_INCIDENCIA = '08';
    case OPERACAO_COM_SUSPENSAO = '09';
    case OUTRAS_OPERACOES_DE_SAIDA = '49';
    case CREDITO_RECEITA_TRIBUTADA_INTERNO = '50';
    case CREDITO_RECEITA_NAO_TRIBUTADA_INTERNO = '51';
    case CREDITO_RECEITA_EXPORTACAO = '52';
    case CREDITO_RECEITAS_TRIBUTADAS_NAO_TRIBUTADAS_INTERNO = '53';
    case CREDITO_RECEITAS_TRIBUTADAS_INTERNO_EXPORTACAO = '54';
    case CREDITO_RECEITAS_NAO_TRIBUTADAS_INTERNO_EXPORTACAO = '55';
    case CREDITO_RECEITAS_TRIBUTADAS_NAO_TRIBUTADAS_INTERNO_EXPORTACAO = '56';
    case CREDITO_PRESUMIDO_RECEITA_TRIBUTADA_INTERNO = '60';
    case CREDITO_PRESUMIDO_RECEITA_NAO_TRIBUTADA_INTERNO = '61';
    case CREDITO_PRESUMIDO_RECEITA_EXPORTACAO = '62';
    case CREDITO_PRESUMIDO_RECEITAS_TRIBUTADAS_NAO_TRIBUTADAS_INTERNO = '63';
    case CREDITO_PRESUMIDO_RECEITAS_TRIBUTADAS_INTERNO_EXPORTACAO = '64';
    case CREDITO_PRESUMIDO_RECEITAS_NAO_TRIBUTADAS_INTERNO_EXPORTACAO = '65';
    case CREDITO_PRESUMIDO_RECEITAS_TRIBUTADAS_NAO_TRIBUTADAS_INTERNO_EXPORTACAO = '66';
    case CREDITO_PRESUMIDO_OUTRAS_OPERACOES = '67';
    case OPERACAO_AQUISICAO_SEM_DIREITO_CREDITO = '70';
    case OPERACAO_AQUISICAO_ISENCAO = '71';
    case OPERACAO_AQUISICAO_SUSPENSAO = '72';
    case OPERACAO_AQUISICAO_ALIQUOTA_ZERO = '73';
    case OPERACAO_AQUISICAO_SEM_INCIDENCIA = '74';
    case OPERACAO_AQUISICAO_SUBSTITUICAO_TRIBUTARIA = '75';
    case OUTRAS_OPERACOES_DE_ENTRADA = '98';
    case OUTRAS_OPERACOES = '99';
}
