<?php

namespace TecnoSpeed\Plugnotas\Enums;

enum OrigemEnum: int
{
    case NACIONAL_EXCETO_3458 = 0;
    case ESTRANGEIRA_IMPORTACAO_DIRETA_EXCETO_6 = 1;
    case ESTRANGEIRA_MERCADO_INTERNO_EXCETO_7 = 2;
    case NACIONAL_IMPORTACAO_40_A_70 = 3;
    case NACIONAL_PROCESSOS_PRODUTIVOS_BASICOS = 4;
    case NACIONAL_IMPORTACAO_ATE_40 = 5;
    case ESTRANGEIRA_IMPORTACAO_SEM_SIMILAR_CAMEX = 6;
    case ESTRANGEIRA_MERCADO_INTERNO_SEM_SIMILAR_CAMEX = 7;
    case NACIONAL_IMPORTACAO_SUPERIOR_70 = 8;
}
